/**
 * Mise Toolchain Integration
 * Handles mise.toml generation and mise commands
 */

import * as fs from 'fs';
import * as path from 'path';
import * as child_process from 'child_process';
import { AgentenvConfig, BINARY_MAP, TOOL_TIERS } from '../config/schema.js';

// Tool to mise name mappings
export const MISE_TOOL_NAMES: Record<string, string> = {
  ripgrep: 'ripgrep',
  fd: 'fd',
  jq: 'jq',
  rtk: 'rtk',
  ast_grep: 'ast-grep',
  git_delta: 'delta',
  universal_ctags: 'universal-ctags',
  gh: 'gh',
  difftastic: 'difftastic',
  yq: 'yq',
  bat: 'bat',
  eza: 'eza',
  miller: 'miller',
  tokei: 'tokei',
  hyperfine: 'hyperfine',
  fzf: 'fzf',
  just: 'just',
  watchexec: 'watchexec',
  direnv: 'direnv',
};

export interface MiseTool {
  name: string;
  miseName: string;
  version: string;
  tier: number;
  category: string;
}

export interface MiseConfig {
  tools: Record<string, string>;
  env?: Record<string, string>;
  settings?: Record<string, any>;
}

/**
 * Generate mise.toml content from agentenv config
 */
export function generateMiseToml(config: AgentenvConfig, customTools: Array<{
  name: string;
  mise_source?: string;
  version?: string;
}> = []): string {
  const lines: string[] = [];
  
  lines.push('# mise.toml - Generated by agentenv');
  lines.push('# Do not edit directly; edit agentenv.toml instead');
  lines.push('');
  
  // Tools section
  lines.push('[tools]');
  
  const tools = config.tools || {};
  const toolKeys = Object.keys(tools) as Array<keyof typeof tools>;
  
  // Process tools by tier
  const tier1Tools = toolKeys.filter(key => TOOL_TIERS[key] === 1 && tools[key]);
  const tier2Tools = toolKeys.filter(key => TOOL_TIERS[key] === 2 && tools[key]);
  const tier3Tools = toolKeys.filter(key => TOOL_TIERS[key] === 3 && tools[key]);
  
  // Add enabled tools
  const allEnabledTools = [...tier1Tools, ...tier2Tools, ...tier3Tools];
  
  for (const toolKey of allEnabledTools) {
    const miseName = MISE_TOOL_NAMES[toolKey] || toolKey;
    const version = 'latest';
    lines.push(`${miseName} = "${version}"`);
  }
  
  // Add custom tools with mise_source
  for (const ct of customTools) {
    if (ct.mise_source) {
      const version = ct.version || 'latest';
      lines.push(`\n# Custom tool: ${ct.name}`);
      lines.push(`${ct.mise_source} = "${version}"`);
    }
  }
  
  lines.push('');
  
  // Env section for agentenv-specific variables
  lines.push('[env]');
  lines.push('AGENTENV_MANAGED = "true"');
  lines.push('');
  
  return lines.join('\n');
}

/**
 * Save mise.toml to a file
 */
export function saveMiseToml(content: string, outputPath: string): void {
  try {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, content);
  } catch (err) {
    throw new Error(`Failed to save mise.toml: ${err}`);
  }
}

/**
 * Get list of tools to install from config
 */
export function getToolsToInstall(config: AgentenvConfig): Array<{
  name: string;
  miseName: string;
  version: string;
  tier: number;
}> {
  const tools = config.tools || {};
  const toolKeys = Object.keys(tools) as Array<keyof typeof tools>;
  
  const result: Array<{
    name: string;
    miseName: string;
    version: string;
    tier: number;
  }> = [];
  
  for (const key of toolKeys) {
    if (tools[key]) {
      const miseName = MISE_TOOL_NAMES[key] || key;
      result.push({
        name: key,
        miseName,
        version: 'latest',
        tier: TOOL_TIERS[key] || 3,
      });
    }
  }
  
  return result;
}

/**
 * Check if mise is installed
 */
export function isMiseInstalled(): boolean {
  try {
    child_process.execSync('mise --version', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Get mise version
 */
export function getMiseVersion(): string {
  try {
    const output = child_process.execSync('mise --version', { encoding: 'utf-8' });
    return output.trim();
  } catch {
    return 'unknown';
  }
}

/**
 * Check if a specific tool is installed via mise
 */
export function isToolInstalled(toolName: string): boolean {
  try {
    child_process.execSync(`mise which ${toolName}`, { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Install mise itself
 * This should be done by the user before running agentenv
 */
export function ensureMiseInstalled(): {
  success: boolean;
  message: string;
} {
  if (isMiseInstalled()) {
    return {
      success: true,
      message: 'mise is already installed',
    };
  }
  
  return {
    success: false,
    message: 'mise is not installed. Please install it first: https://mise.jdx.dev',
  };
}

/**
 * Run mise install
 * Installs all tools listed in mise.toml
 */
export async function runMiseInstall(miseTomlPath: string, cwd: string = '.'): Promise<{
  success: boolean;
  stdout: string;
  stderr: string;
  exitCode: number | null;
}> {
  try {
    const result = child_process.spawnSync(
      'mise',
      ['install'],
      {
        cwd,
        encoding: 'utf-8',
        stdio: 'pipe',
        env: {
          ...process.env,
          // Ensure mise uses the correct config file
          MISE_CONFIG_FILE: miseTomlPath,
        },
      }
    );
    
    return {
      success: result.status === 0,
      stdout: result.stdout || '',
      stderr: result.stderr || '',
      exitCode: result.status ?? null,
    };
  } catch (err) {
    return {
      success: false,
      stdout: '',
      stderr: err instanceof Error ? err.message : String(err),
      exitCode: null,
    };
  }
}

/**
 * Get installed tool versions via mise
 */
export function getInstalledVersions(): Record<string, string> {
  const versions: Record<string, string> = {};
  
  try {
    const output = child_process.execSync('mise ls --json', {
      encoding: 'utf-8',
      stdio: 'pipe',
    });
    
    const tools = JSON.parse(output) as Array<{
      name: string;
      version: string;
    }>;
    
    for (const tool of tools) {
      versions[tool.name] = tool.version;
    }
  } catch {
    // Ignore errors (mise might not be installed or might not support --json)
  }
  
  return versions;
}

/**
 * Parse existing mise.toml file
 */
export function parseMiseToml(filePath: string): MiseConfig | null {
  try {
    if (!fs.existsSync(filePath)) {
      return null;
    }
    
    const content = fs.readFileSync(filePath, 'utf-8');
    return parseToml(content) as MiseConfig;
  } catch {
    return null;
  }
}

/**
 * Simple TOML parser helper
 */
function parseToml(content: string): Record<string, any> {
  const result: Record<string, any> = {};
  let currentSection = '';
  let currentTable: Record<string, any> = result;
  
  const lines = content.split('\n');
  
  for (const line of lines) {
    const trimmed = line.trim();
    
    // Skip comments and empty lines
    if (trimmed === '' || trimmed.startsWith('#')) {
      continue;
    }
    
    // Section header
    if (trimmed.startsWith('[') && trimmed.endsWith(']')) {
      const section = trimmed.slice(1, -1);
      
      if (section.includes('.')) {
        // Nested section
        const parts = section.split('.');
        let parent: Record<string, any> = result;
        
        for (let i = 0; i < parts.length - 1; i++) {
          if (!parent[parts[i]]) {
            parent[parts[i]] = {};
          }
          parent = parent[parts[i]];
        }
        
        currentSection = parts[parts.length - 1];
        currentTable = parent;
      } else {
        currentSection = section;
        if (!result[section]) {
          result[section] = {};
        }
        currentTable = result[section];
      }
      continue;
    }
    
    // Key-value pair
    const equalsIndex = trimmed.indexOf('=');
    if (equalsIndex > 0) {
      const key = trimmed.slice(0, equalsIndex).trim();
      const value = trimmed.slice(equalsIndex + 1).trim();
      
      // Remove quotes if present
      let cleanValue: any = value;
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        cleanValue = value.slice(1, -1);
      }
      
      // Parse boolean
      if (cleanValue.toLowerCase() === 'true') {
        cleanValue = true;
      } else if (cleanValue.toLowerCase() === 'false') {
        cleanValue = false;
      }
      
      // Parse number
      if (!isNaN(Number(cleanValue))) {
        cleanValue = Number(cleanValue);
      }
      
      currentTable[key] = cleanValue;
    }
  }
  
  return result;
}

/**
 * Merge existing mise.toml with new tools
 * Preserves existing tools that are not in the new config
 */
export function mergeMiseConfigs(existing: MiseConfig | null, newConfig: MiseConfig): MiseConfig {
  const result: MiseConfig = {
    tools: { ...newConfig.tools },
    env: { ...newConfig.env },
    settings: { ...newConfig.settings },
  };
  
  if (existing) {
    // Merge tools - preserve existing versions if not in new config
    for (const [tool, version] of Object.entries(existing.tools || {})) {
      if (!result.tools[tool]) {
        result.tools[tool] = version;
      }
    }
    
    // Merge env
    if (existing.env) {
      for (const [key, value] of Object.entries(existing.env)) {
        if (!result.env || !result.env[key]) {
          if (!result.env) {
            result.env = {};
          }
          result.env[key] = value;
        }
      }
    }
    
    // Merge settings
    if (existing.settings) {
      for (const [key, value] of Object.entries(existing.settings)) {
        if (!result.settings || result.settings[key] === undefined) {
          if (!result.settings) {
            result.settings = {};
          }
          result.settings[key] = value;
        }
      }
    }
  }
  
  return result;
}
