/**
 * Mise Toolchain Integration
 * Handles mise.toml generation and mise commands
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as child_process from 'child_process';
import { AgentenvConfig, BINARY_MAP, TOOL_KEYS, TOOL_TIERS } from '../config/schema.js';
import { resolveBinary } from '../adapters/detect.js';
import { writeFileWithVerify } from '../utils/fs-retry.js';
import { FALLBACK_REQUIRED_TOOLS, isPlatformUnsupported, requiresFallback } from './fallbacks.js';
import { failGlyph, successGlyph } from '../ui/theme.js';
import {
  mergeShellFixEntries,
  readShellFixState,
  writeShellFixState,
} from '../shell/shell-fix-state.js';

// Tool to mise name mappings
export const MISE_TOOL_NAMES: Record<string, string> = {
  ripgrep: 'ripgrep',
  fd: 'fd',
  jq: 'jq',
  rtk: 'rtk',
  ast_grep: 'ast-grep',
  git_delta: 'delta',
  gh: 'gh',
  difftastic: 'difftastic',
  yq: 'yq',
  bat: 'bat',
  eza: 'eza',
  miller: 'miller',
  tokei: 'tokei',
  hyperfine: 'hyperfine',
  fzf: 'fzf',
  just: 'just',
  watchexec: 'watchexec',
  direnv: 'direnv',
  // New tools
  ripgrep_all: 'ripgrep-all',
  zoxide: 'zoxide',
  shellcheck: 'shellcheck',
  uv: 'uv',
  xh: 'xh',
  actionlint: 'actionlint',
  gitleaks: 'gitleaks',
  gum: 'gum',
  glow: 'glow',
  jless: 'jless',
  sd: 'sd',
  tealdeer: 'tealdeer',
  duckdb: 'duckdb',
  qsv: 'qsv',
  taplo: 'taplo',
  hadolint: 'hadolint',
  trivy: 'trivy',
};

// Tools that cannot be installed via mise and require fallback
// Based on Phase 0 findings: tokei is not in the mise registry (needs cargo backend)
export { FALLBACK_REQUIRED_TOOLS, isPlatformUnsupported, requiresFallback };

export interface MiseTool {
  name: string;
  miseName: string;
  version: string;
  tier: number;
  category: string;
}

/**
 * Tools agentenv invokes directly are pinned to versions we have verified;
 * everything else resolves to latest. rtk is invoked by agentenv's delegation
 * (its `init` flags are the hook contract), moves fast, and must stay pinned —
 * bump deliberately per plan §10. A catalog tool is also pinned when its
 * `latest` release is currently broken upstream (mise's aqua backend cannot
 * install it), so the generated mise.toml ships a known-good version instead
 * of reproducing the upstream failure on every user machine.
 */
export const PINNED_TOOL_VERSIONS: Record<string, string> = {
  rtk: '0.49.0',
  // difftastic 0.71.0+ renamed its release assets to `difft-<version>-…`
  // (unversioned before), which the aqua registry's asset template does not
  // match on any platform — `mise install` fails with "no asset found:
  // difft-x86_64-unknown-linux-musl.tar.gz". 0.70.0 is the last verified
  // installable release (phase0 research docs). Unpin when upstream fixes
  // the asset naming or mise resolves it for us.
  difftastic: '0.70.0',
};

/**
 * Generate mise.toml content from agentenv config
 */
export function generateMiseToml(
  config: AgentenvConfig,
  customTools: Array<{
    name: string;
    mise_source?: string;
    version?: string;
  }> = [],
): string {
  const lines: string[] = [];

  lines.push('# mise.toml - Generated by agentenv');
  lines.push('# Do not edit directly; edit agentenv.toml instead');
  lines.push('');

  // Tools section
  lines.push('[tools]');

  const tools = config.tools || {};
  const toolKeys = Object.keys(tools) as Array<keyof typeof tools>;

  // Process tools by tier
  const tier1Tools = toolKeys.filter((key) => TOOL_TIERS[key] === 1 && tools[key]);
  const tier2Tools = toolKeys.filter((key) => TOOL_TIERS[key] === 2 && tools[key]);
  const tier3Tools = toolKeys.filter((key) => TOOL_TIERS[key] === 3 && tools[key]);

  // Add enabled tools
  const allEnabledTools = [...tier1Tools, ...tier2Tools, ...tier3Tools];

  for (const toolKey of allEnabledTools) {
    // Skip tools that require fallback installation (not in mise registry)
    if (requiresFallback(toolKey) || isPlatformUnsupported(toolKey)) {
      continue;
    }
    const miseName = MISE_TOOL_NAMES[toolKey] || toolKey;
    const version = PINNED_TOOL_VERSIONS[miseName] || config.tool_versions?.[toolKey] || 'latest';
    lines.push(`${miseName} = "${version}"`);
  }

  // Add custom tools with mise_source
  for (const ct of customTools) {
    if (ct.mise_source) {
      const version = ct.version || 'latest';
      lines.push(`\n# Custom tool: ${ct.name}`);
      lines.push(`${ct.mise_source} = "${version}"`);
    }
  }

  lines.push('');

  // Env section for agentenv-specific variables
  lines.push('[env]');
  lines.push('AGENTENV_MANAGED = "true"');
  lines.push('');

  return lines.join('\n');
}

/**
 * Directory where agentenv asks mise to place shims. Shim files are what make
 * the installed tools resolve by name ("difft", "rg", ...) from any shell —
 * PowerShell, cmd, bash or the agents themselves.
 *
 * Precedence mirrors mise: a non-empty, absolute `MISE_SHIMS_DIR` env var wins
 * (mise binds it to the `shims_dir` setting, which must resolve to an absolute
 * path), else the default agentenv writes into the global config (`~/.local/bin`).
 * Honoring the override keeps agentenv's shim-existence checks pointed at the
 * directory mise actually populates instead of the configured default.
 */
export function shimsDir(): string {
  const override = process.env.MISE_SHIMS_DIR;
  if (override && override.trim() !== '') {
    const expanded = expandLeadingTilde(override);
    if (path.isAbsolute(expanded)) return expanded;
  }
  return path.join(os.homedir(), '.local', 'bin');
}

/**
 * Expand a single leading `~` (bare or `~/…`/`~\…`) to the home directory,
 * mirroring mise's `replace_path` for path-valued env vars. Anything else is
 * returned unchanged.
 */
function expandLeadingTilde(p: string): string {
  if (p === '~') return os.homedir();
  if (p.startsWith('~/') || p.startsWith('~\\')) return path.join(os.homedir(), p.slice(2));
  return p;
}

/**
 * mise's global config directory, resolved the same way mise resolves it —
 * `MISE_CONFIG_DIR`, else an absolute `$XDG_CONFIG_HOME/mise`, else
 * `~/.config/mise`. `shims_dir` is a global-only setting: mise strips it from
 * any config it does not consider global and warns ("ignored for security
 * reasons"), so it must land in the file mise actually reads. A custom
 * `XDG_CONFIG_HOME` (common in Linux dotfile setups) otherwise points the two
 * at different directories. agentenv likewise never points `MISE_CONFIG_FILE`
 * at a project `mise.toml` (see {@link miseSpawnOptions}) — doing so would
 * demote this file and re-trigger that warning.
 */
export function miseGlobalConfigDir(): string {
  const override = process.env.MISE_CONFIG_DIR;
  if (override && override.trim() !== '') return expandLeadingTilde(override);
  const xdg = process.env.XDG_CONFIG_HOME;
  if (xdg && path.isAbsolute(xdg)) return path.join(xdg, 'mise');
  return path.join(os.homedir(), '.config', 'mise');
}

export function miseGlobalConfigPath(): string {
  return path.join(miseGlobalConfigDir(), 'config.toml');
}

/**
 * True when a PATH variable entry resolves to the given directory
 * (case-folded on Windows where PATH entries and real paths often differ in
 * case).
 */
export function pathContainsDir(pathVar: string, dir: string): boolean {
  const target = path.resolve(dir);
  const want = process.platform === 'win32' ? target.toLowerCase() : target;
  return pathVar
    .split(path.delimiter)
    .filter((entry) => entry.trim() !== '')
    .some((entry) => {
      const resolved = path.resolve(entry);
      const have = process.platform === 'win32' ? resolved.toLowerCase() : resolved;
      return have === want;
    });
}

/** Whether the shims dir (~/.local/bin) is already resolvable from PATH. */
export function shimsDirOnPath(): boolean {
  return pathContainsDir(process.env.PATH ?? '', shimsDir());
}

/**
 * Line-based insert/update of `shims_dir = "<dir>"` under `[settings]` in a
 * mise config. Surgical on purpose: the global mise config may carry the
 * user's own comments/settings, and a full TOML round-trip would destroy them.
 */
export function upsertShimsDir(content: string, dir: string): string {
  const shimsLine = `shims_dir = "${tomlPath(dir)}"`;
  const lines = content.split('\n');
  const headerIdx = lines.findIndex((line) => /^\s*\[settings\]\s*$/.test(line));
  if (headerIdx === -1) {
    const trimmed = content.trimEnd();
    return trimmed === ''
      ? `[settings]\n${shimsLine}\n`
      : `${trimmed}\n\n[settings]\n${shimsLine}\n`;
  }
  const nextHeader = lines.findIndex((line, i) => i > headerIdx && /^\s*\[[^[]/.test(line));
  const end = nextHeader === -1 ? lines.length : nextHeader;
  const existing = lines.slice(headerIdx, end).findIndex((line) => /^\s*shims_dir\s*=/.test(line));
  if (existing !== -1) {
    lines[headerIdx + existing] = shimsLine;
    return lines.join('\n');
  }
  lines.splice(headerIdx + 1, 0, shimsLine);
  return lines.join('\n');
}

/**
 * Extract the `shims_dir` value mise would honor from `[settings]` in a mise
 * config, or null when it is absent. Used by `agentenv doctor`.
 */
export function getShimsDirValue(content: string): string | null {
  const lines = content.split('\n');
  const headerIdx = lines.findIndex((line) => /^\s*\[settings\]\s*$/.test(line));
  if (headerIdx === -1) return null;
  for (let i = headerIdx + 1; i < lines.length; i++) {
    if (/^\s*\[[^[]/.test(lines[i])) break;
    const match = lines[i].match(/^\s*shims_dir\s*=\s*"([^"]+)"/);
    if (match) return match[1];
  }
  return null;
}

/**
 * Remove the `shims_dir` line that upsertShimsDir writes and, if that leaves
 * the `[settings]` section with no other keys, the section header too ("other
 * keys" means any non-empty line between the header and the next section).
 * Returns the content unchanged when no `shims_dir` line is present. Surgical
 * counterpart to upsertShimsDir, used by `shell-fix --revert`.
 */
export function removeShimsDirValue(content: string): string {
  const lines = content.split(/\r?\n/);
  const shimsIdx = lines.findIndex((line) => /^\s*shims_dir\s*=/.test(line.trim()));
  if (shimsIdx === -1) return content;
  lines.splice(shimsIdx, 1);

  const headerIdx = lines.findIndex((line) => /^\s*\[settings\]\s*$/.test(line.trim()));
  if (headerIdx !== -1) {
    let empty = true;
    for (let i = headerIdx + 1; i < lines.length; i++) {
      const trimmed = lines[i].trim();
      if (/^\s*\[.*\]$/.test(trimmed)) break;
      if (trimmed !== '') {
        empty = false;
        break;
      }
    }
    if (empty) {
      lines.splice(headerIdx, 1);
      if (lines[headerIdx]?.trim() === '') lines.splice(headerIdx, 1);
    }
  }

  while (lines.length > 0 && lines[lines.length - 1].trim() === '') lines.pop();
  return lines.length > 0 ? `${lines.join('\n')}\n` : '';
}

/**
 * Ensure mise's GLOBAL config declares the shims_dir agentenv relies on, and
 * tell the user whether the shims dir is actually on PATH. Idempotent.
 *
 * When `statePath` is given, a change made here is recorded in the shell-fix
 * manifest (agent `mise`) so `agentenv shell-fix --revert` can undo it. The
 * existing manifest's bashExe is preserved when merging so a Tier 0 entry and
 * the mise entry coexist in one apply run without clobbering each other's
 * revert comparison value.
 */
export function ensureGlobalShimsDir(statePath?: string): {
  success: boolean;
  message: string;
} {
  const dir = shimsDir();
  const configPath = miseGlobalConfigPath();
  try {
    fs.mkdirSync(miseGlobalConfigDir(), { recursive: true });
    const existing = fs.existsSync(configPath) ? fs.readFileSync(configPath, 'utf-8') : '';
    const updated = upsertShimsDir(existing, dir);
    if (updated !== existing) {
      fs.writeFileSync(configPath, updated);
      if (statePath) {
        recordShimsDirState(configPath, existing, tomlPath(dir), statePath);
      }
    }

    const pathLine = shimsDirOnPath()
      ? `${dir} is on PATH`
      : `Add ${dir} to PATH so the shims resolve (Windows: System Properties > Environment Variables > Path)`;
    if (updated !== existing) {
      return {
        success: true,
        message: `mise: set shims_dir in ${configPath}; ${pathLine}`,
      };
    }
    return {
      success: true,
      message: `mise: shims_dir already set (${tomlPath(dir)}); ${pathLine}`,
    };
  } catch (err) {
    return {
      success: false,
      message: `Failed to configure mise shims_dir: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}

/** Format a path for embedding in a TOML string (mise wants forward slashes). */
function tomlPath(p: string): string {
  return p.replace(/\\/g, '/');
}

/**
 * Record a mise shims_dir write in the shell-fix manifest, preserving the
 * existing manifest's bashExe so Tier 0 entries keep comparing against the
 * git-bash path they were written with. Advisory: a recording failure must
 * never fail the (already-successful) shims config itself.
 */
function recordShimsDirState(
  configPath: string,
  existing: string,
  setValue: string,
  statePath: string,
): void {
  try {
    const existingState = readShellFixState(statePath);
    writeShellFixState(
      mergeShellFixEntries(
        existingState,
        [
          {
            agent: 'mise',
            file: configPath,
            createdFile: existing === '',
            fields: [{ key: 'shims_dir', previous: getShimsDirValue(existing), set: setValue }],
          },
        ],
        existingState?.bashExe ?? setValue,
      ),
      statePath,
    );
  } catch {
    // Recording is advisory; the fix itself already succeeded.
  }
}

/**
 * Save mise.toml to a file
 */
export function saveMiseToml(content: string, outputPath: string): void {
  try {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    const result = writeFileWithVerify(outputPath, content);
    if (!result.success) throw new Error(result.message);
  } catch (err) {
    throw new Error(
      `Failed to save mise.toml: ${err instanceof Error ? err.message : String(err)}`,
      { cause: err },
    );
  }
}

/**
 * Get list of tools to install from config
 */
export function getToolsToInstall(config: AgentenvConfig): Array<{
  name: string;
  miseName: string;
  version: string;
  tier: number;
}> {
  const tools = config.tools || {};
  const toolKeys = Object.keys(tools) as Array<keyof typeof tools>;

  const result: Array<{
    name: string;
    miseName: string;
    version: string;
    tier: number;
  }> = [];

  for (const key of toolKeys) {
    if (tools[key]) {
      // Skip tools that require fallback installation (not in mise registry)
      if (requiresFallback(key) || isPlatformUnsupported(key)) {
        continue;
      }
      const miseName = MISE_TOOL_NAMES[key] || key;
      result.push({
        name: key,
        miseName,
        version: PINNED_TOOL_VERSIONS[miseName] || config.tool_versions?.[key] || 'latest',
        tier: TOOL_TIERS[key] || 3,
      });
    }
  }

  return result;
}

/**
 * The mise tool names `agentenv update` may safely bump: enabled, non-fallback
 * tools that resolve to `latest`. Pinned tools (rtk's code pin and any
 * `agentenv.toml [tool_versions]` entry) are excluded so `mise up` never moves
 * a version the user (or the hook contract) chose to pin.
 */
export function getUpgradeableTools(config: AgentenvConfig): string[] {
  return getToolsToInstall(config)
    .filter((tool) => tool.version === 'latest')
    .map((tool) => tool.miseName);
}

/**
 * Update mise itself. Unattended (`MISE_YES=1`); surfaces stderr as-is because
 * some install methods (e.g. winget) do not support in-place self-updates and
 * the user must see that instead of a silent no-op.
 */
export async function runMiseSelfUpdate(): Promise<{
  success: boolean;
  output: string;
}> {
  try {
    const result = child_process.spawnSync('mise', ['self-update'], {
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, MISE_YES: '1' },
      timeout: 60000,
    });
    const output = (result.stdout || result.stderr || '').trim();
    return { success: result.status === 0, output };
  } catch (err) {
    return {
      success: false,
      output: err instanceof Error ? err.message : String(err),
    };
  }
}

/**
 * Bump the given `mise up` targets to their latest versions within the current
 * config constraints (pins stay put because pinned tools are not passed in).
 */
export async function runMiseUpgrade(
  tools: string[],
  cwd: string,
): Promise<{
  success: boolean;
  stdout: string;
  stderr: string;
  exitCode: number | null;
}> {
  try {
    const result = child_process.spawnSync('mise', ['up', ...tools], {
      cwd,
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'pipe'],
      timeout: 120000,
    });
    return {
      success: result.status === 0,
      stdout: result.stdout || '',
      stderr: result.stderr || '',
      exitCode: result.status ?? null,
    };
  } catch (err) {
    return {
      success: false,
      stdout: '',
      stderr: err instanceof Error ? err.message : String(err),
      exitCode: null,
    };
  }
}

/**
 * Uninstall the given tools from the mise store. Each tool name is passed
 * version-less (no `@version`) together with `--all`, removing every installed
 * version of that tool. `--all` is required: without it, mise 2026.x bails with
 * "multiple tools specified, use --all to uninstall all versions" as soon as a
 * named tool has more than one version installed. Surfaces the captured
 * subprocess result like runMiseUpgrade does.
 */
export function runMiseUninstall(
  tools: string[],
  cwd: string = '.',
  miseTomlPath?: string,
): {
  success: boolean;
  stdout: string;
  stderr: string;
  exitCode: number | null;
} {
  // Deleting installed tool files can take longer than a metadata query.
  const result = runMiseCaptured(['uninstall', '--all', ...tools], {
    cwd,
    miseTomlPath,
    timeoutMs: 60000,
  });
  return {
    success: result.status === 0,
    stdout: result.stdout || '',
    stderr: result.stderr || '',
    exitCode: result.status ?? null,
  };
}

export interface RunMiseCapturedOptions {
  cwd?: string;
  /**
   * Path to the generated project `mise.toml`. Used only to derive the working
   * directory when `cwd` is omitted — mise discovers the file as a local config
   * from there. It is deliberately NOT passed as `MISE_CONFIG_FILE`; see
   * {@link miseSpawnOptions} for why.
   */
  miseTomlPath?: string;
  /**
   * Max time to wait before killing a hung `mise` (a stuck network call would
   * otherwise freeze `status`/`doctor`/`apply` indefinitely). Default 30s
   * covers this funnel's normal callers (--version/which/trust/ls); callers
   * expecting more work (e.g. uninstall) pass a longer one.
   */
  timeoutMs?: number;
}

/**
 * Build the working directory and environment for a mise invocation.
 *
 * `miseTomlPath` selects the directory to run from so mise discovers the
 * generated `mise.toml` as a *local* config. It must never be exported as
 * `MISE_CONFIG_FILE`: mise treats that variable as its **global** config file
 * (`MISE_GLOBAL_CONFIG_FILE` falls back to `MISE_CONFIG_FILE`), so pointing it
 * at a project file demotes the real global config
 * (`~/.config/mise/config.toml`) to a non-global one. mise then strips
 * global-only settings from it — including `shims_dir` — and warns
 * "shims_dir in non-global config ... is ignored for security reasons".
 * Running from the containing directory instead keeps the global config global.
 */
export function miseSpawnOptions(opts: RunMiseCapturedOptions = {}): {
  cwd: string | undefined;
  env: NodeJS.ProcessEnv;
} {
  const cwd = opts.cwd ?? (opts.miseTomlPath ? path.dirname(opts.miseTomlPath) : undefined);
  return { cwd, env: process.env };
}

export interface MiseCapturedOutput {
  status: number | null;
  stdout: string;
  stderr: string;
}

/**
 * Run a single mise command with args passed as an array (never a
 * string-built command — paths with spaces would break parsing on Windows)
 * and with stderr captured instead of inherited. This is the one funnel every
 * mise capture goes through so a `mise WARN` update notice on stderr can
 * never leak into agentenv's stdout.
 */
export function runMiseCaptured(
  args: string[],
  opts: RunMiseCapturedOptions = {},
): MiseCapturedOutput {
  const { cwd, env } = miseSpawnOptions(opts);
  let result: child_process.SpawnSyncReturns<string>;
  try {
    result = child_process.spawnSync('mise', args, {
      cwd,
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'pipe'],
      env,
      timeout: opts.timeoutMs ?? 30000,
    });
  } catch (err) {
    return {
      status: null,
      stdout: '',
      stderr: err instanceof Error ? err.message : String(err),
    };
  }
  const stderr = result.error ? result.error.message : (result.stderr ?? '');
  return {
    status: result.status,
    stdout: result.stdout ?? '',
    stderr,
  };
}

/**
 * Check if a specific tool is installed via mise
 */
export function isMiseInstalled(): boolean {
  return runMiseCaptured(['--version']).status === 0;
}

/**
 * Get mise version. The probe is silent by construction: it only reads
 * stdout, never surfaces whatever mise may have written to stderr (a
 * `mise WARN release available` update notice is not truth about the
 * installed version, so it is dropped here).
 */
export function getMiseVersion(): string {
  const result = runMiseCaptured(['--version']);
  const version = result.stdout.trim();
  return result.status === 0 && version !== '' ? version : 'unknown';
}

/**
 * Check if a specific tool is installed via mise
 */
export function isToolInstalled(toolName: string): boolean {
  return runMiseCaptured(['which', toolName]).status === 0;
}

/**
 * Install mise itself
 * This should be done by the user before running agentenv
 */
export function ensureMiseInstalled(): {
  success: boolean;
  message: string;
} {
  if (isMiseInstalled()) {
    return {
      success: true,
      message: `mise is already installed (${getMiseVersion()})`,
    };
  }

  return {
    success: false,
    message:
      "mise is not installed. agentenv uses mise to install and manage this project's tools.\n" +
      miseInstallInstructions().join('\n'),
  };
}

/**
 * The literal "Prerequisite: mise X" line, built from a version string so
 * setup/configure/apply all render identically without drifting.
 */
export function prereqLine(version: string): string {
  return `Prerequisite: mise ${version}`;
}

/**
 * The shared "Prerequisite: mise X" string, resolved from the real mise. Both
 * paths that funnel into `apply` (setup/configure) can tell apply "we already
 * printed it" without the line drifting.
 */
export function prereqMessage(): string {
  return prereqLine(getMiseVersion());
}

/**
 * Platform-specific instructions for installing mise, used for self-diagnosis
 * when `mise` is missing from PATH.
 */
export function miseInstallInstructions(): string[] {
  const lines = ['To install mise, run one of the following:'];

  if (process.platform === 'win32') {
    lines.push('  winget install jdx.mise');
    lines.push('  # or: irm https://mise.jdx.dev/install.ps1 | iex');
  } else if (process.platform === 'darwin') {
    lines.push('  brew install mise');
  } else {
    lines.push('  curl https://mise.jdx.dev/install.sh | sh');
  }

  lines.push('Then open a new terminal so `mise` is available on PATH.');
  lines.push('Full docs: https://mise.jdx.dev/getting-started.html');
  return lines;
}

/**
 * Mark the generated mise.toml as trusted so `mise` (and the shims it creates)
 * actually use it in this directory. Idempotent: re-trusting is a no-op success.
 */
export function trustMiseToml(
  miseTomlPath: string,
  cwd: string = '.',
): {
  success: boolean;
  message: string;
} {
  const result = runMiseCaptured(['trust', miseTomlPath], { cwd });
  if (result.status === 0) {
    return { success: true, message: `Trusted ${miseTomlPath} (mise trust)` };
  }
  const detail = (result.stderr || result.stdout || '').trim();
  if (result.status === null && detail) {
    return { success: false, message: `mise trust errored: ${detail}` };
  }
  return {
    success: false,
    message: `mise trust failed (exit ${result.status ?? 'null'}): ${detail}`,
  };
}

/**
 * Turn raw `mise install` output into a truthful one-liner, so "already
 * installed" runs don't imply anything new was fetched.
 */
export function miseInstallOutcome(stdout: string): string {
  const match = stdout.match(/installed (\d+) tools?/);
  if (match) {
    const installed = Number(match[1]);
    if (installed === 0)
      return 'mise install completed (tools already installed, nothing to fetch)';
    return `mise install completed (installed ${installed} tool${installed === 1 ? '' : 's'})`;
  }
  return 'mise install completed';
}

export type ToolResolvability = 'resolvable' | 'needs-new-terminal' | 'manual' | 'missing';

export interface ToolAvailability {
  key: string;
  binary: string;
  onPath: boolean;
  status: ToolResolvability;
}

/**
 * True when a shim file for `binary` exists on disk under `dir` (case-folded,
 * and accepting the .exe/.cmd/.bat suffix Windows shims get). This is what
 * distinguishes "installed, just not on this stale PATH's resolve set" from
 * "not installed at all" — a new terminal picks the shim up from here.
 */
export function shimExistsIn(binary: string, dir: string): boolean {
  let entries: string[];
  try {
    entries = fs.readdirSync(dir);
  } catch {
    return false;
  }
  const base = binary.toLowerCase();
  return entries.some((entry) => {
    const name = entry.toLowerCase();
    return (
      name === base || name === `${base}.exe` || name === `${base}.cmd` || name === `${base}.bat`
    );
  });
}

/** Whether the shim for `binary` exists in the common shims dir (~/.local/bin). */
export function shimExists(binary: string): boolean {
  return shimExistsIn(binary, shimsDir());
}

/**
 * The three-state verdict for one binary. `resolvable` means it is on the
 * current PATH; `needs-new-terminal` means it is installed (mise's own store
 * reports it, or a mise shim exists on disk) but the current shell's PATH is
 * stale; `missing` means neither — the only case that is a genuine failure.
 * (`manual` is assigned by `toolAvailabilityClassification` /
 * `verifyToolAvailability`, not here: it marks tools agentenv never hands to
 * mise, so they can never be "missing".)
 */
export function classifyToolResolvability(
  onPath: boolean,
  shimPresent: boolean,
  isWindows: boolean = process.platform === 'win32',
  miseInstalled = false,
): ToolResolvability {
  if (onPath) return 'resolvable';
  // mise's store is authoritative: a tool it reports installed is not
  // "missing" just because this shell cannot resolve it yet. Windows in
  // particular installs project tools without always leaving a shim in the
  // shims dir, which previously made a successful install fail verification.
  if (miseInstalled) return 'needs-new-terminal';
  if (isWindows && shimPresent) return 'needs-new-terminal';
  return 'missing';
}

export function toolResolvability(binary: string): ToolResolvability {
  return classifyToolResolvability(resolveBinary(binary) !== null, shimExists(binary));
}

/**
 * The single per-tool verdict both the write pipelines (`verifyToolAvailability`)
 * and the read-only commands (`status`, `doctor`) use, so they can never drift
 * apart: tools with no mise fallback on this platform are `manual` (agentenv
 * never hands them to mise, so they are never "missing"), and a tool mise
 * reports as installed is `needs-new-terminal`, not drift. `resolveFn` and
 * `shimCheck` honor the injectable dependencies the status command passes in
 * tests so a result cannot depend on the machine the test runs on.
 */
export function toolAvailabilityClassification(
  key: string,
  binary: string,
  installedState: Record<string, InstalledToolState>,
  resolveFn: (binary: string) => string | null = resolveBinary,
  shimCheck: (binary: string) => boolean = shimExists,
): ToolResolvability {
  if (requiresFallback(key) || isPlatformUnsupported(key)) {
    // A tool agentenv never hands to mise (tokei) or can't install on this
    // platform (jless/rga on Windows) may still be present on PATH: e.g.
    // `apt install tokei` → /usr/bin/tokei on Linux. Report it as installed
    // then; only absent ones are "manual / install manually", never drift.
    return resolveFn(binary) !== null ? 'resolvable' : 'manual';
  }
  const miseName = MISE_TOOL_NAMES[key] ?? key;
  const onPath = resolveFn(binary) !== null;
  return classifyToolResolvability(
    onPath,
    shimCheck(binary),
    undefined,
    installedState[miseName]?.installed === true,
  );
}

export interface VerifyToolOptions {
  /** Pre-fetched `mise ls --json` state; fetched lazily from mise when omitted. */
  installedState?: Record<string, InstalledToolState>;
  /** cwd / mise.toml for the lazy `mise ls --json` probe (scope-aware). */
  cwd?: string;
  miseTomlPath?: string;
  /** Injectable PATH resolver; defaults to the real `resolveBinary`. */
  resolveFn?: (binary: string) => string | null;
  /** Injectable shim check; defaults to the real `shimExists`. */
  shimCheck?: (binary: string) => boolean;
}

/**
 * After `mise install`, check which enabled tools actually resolve on PATH so
 * setup/apply can report honestly whether shims are active in this shell. A tool
 * mise reports as installed but that is not on this shell's PATH is classified
 * `needs-new-terminal`, not `missing` — on Windows (and any shell without mise
 * activation) that is the difference between a truthful hint and a false apply
 * failure.
 */
export function verifyToolAvailability(
  config: AgentenvConfig,
  options: VerifyToolOptions = {},
): ToolAvailability[] {
  const installedState =
    options.installedState ??
    getInstalledToolState(undefined, { cwd: options.cwd, miseTomlPath: options.miseTomlPath });
  const tools = config.tools || {};
  const result: ToolAvailability[] = [];
  const resolveFn = options.resolveFn ?? resolveBinary;
  const shimCheck = options.shimCheck ?? shimExists;
  for (const key of TOOL_KEYS) {
    if (tools[key] !== true) continue;
    const binary = BINARY_MAP[key];
    result.push({
      key,
      binary,
      onPath: resolveFn(binary) !== null,
      status: toolAvailabilityClassification(key, binary, installedState, resolveFn, shimCheck),
    });
  }
  return result;
}

export interface VerifyCounts {
  resolvable: number;
  needsNewTerminal: number;
  manual: number;
  missing: number;
}

export function verifyCounts(availability: ToolAvailability[]): VerifyCounts {
  const counts: VerifyCounts = { resolvable: 0, needsNewTerminal: 0, manual: 0, missing: 0 };
  for (const tool of availability) {
    if (tool.status === 'resolvable') counts.resolvable++;
    else if (tool.status === 'needs-new-terminal') counts.needsNewTerminal++;
    else if (tool.status === 'manual') counts.manual++;
    else counts.missing++;
  }
  return counts;
}

/**
 * Shared summary line used by `apply` and `update`. The old
 * "N/M configured tools resolve on PATH" phrasing is kept only as a superset
 * when something is not immediately resolvable.
 */
export function verifySummaryLine(availability: ToolAvailability[]): string {
  const counts = verifyCounts(availability);
  const manual = counts.manual > 0 ? ` / ${counts.manual} manual` : '';
  const base = `Verify: ${counts.resolvable} resolvable / ${counts.needsNewTerminal} need a new terminal${manual} / ${counts.missing} missing`;
  if (counts.needsNewTerminal + counts.missing > 0) {
    return `${base} — ${counts.resolvable}/${availability.length} configured tools resolve on PATH now`;
  }
  return base;
}

/** One line per tool, symbol-prefixed (commands add their own indentation). */
export function toolAvailabilityLine(tool: ToolAvailability): string {
  if (tool.status === 'resolvable') return `${successGlyph()} ${tool.binary} (${tool.key})`;
  if (tool.status === 'needs-new-terminal') {
    return `~ ${tool.binary} (${tool.key}) — installed; open a new terminal`;
  }
  if (tool.status === 'manual') {
    return `- ${tool.binary} (${tool.key}) — not managed by mise; install manually`;
  }
  return `${failGlyph()} ${tool.binary} (${tool.key}) — not installed (mise install did not produce it)`;
}

/**
 * Whether the activation hint should be shown at all: only when at least one
 * tool is installed-but-stale or missing. Emitted once per run by the caller.
 */
export function verifyHintNeeded(availability: ToolAvailability[]): boolean {
  return availability.some(
    (tool) => tool.status === 'needs-new-terminal' || tool.status === 'missing',
  );
}

/**
 * Concise, actionable guidance for the case where tools are installed via mise
 * but are not yet resolvable from the current shell.
 */
export function miseActivationHint(): string {
  if (process.platform === 'win32') {
    return [
      'Tools ARE installed via mise and resolve inside this project (shims in ~/.local/bin).',
      "If one still isn't found: open a NEW terminal in this project, or run `mise trust` + `mise install`, or `mise use -g <tool>`.",
    ].join('\n');
  }
  return [
    'Enable mise in your shell so tools resolve on PATH: add `eval "$(mise activate bash)"` to ~/.bashrc (or `mise activate zsh` for zsh).',
    'Then start a new terminal.',
  ].join('\n');
}

/**
 * Patterns that indicate an interactive acceptance prompt (EULA/license) in
 * install output. Detected so the user is told *which* tool wants acceptance
 * with a one-line instruction instead of a deadlocked/hung non-interactive run.
 */
export const EULA_PROMPT_PATTERNS: RegExp[] = [
  /\beula\b/i,
  /accept.*(?:license|terms|eula)/i,
  /\by\/n\b/i,
  /\bpress\s+(?:enter|y)\b/i,
];

/**
 * Known tools whose first install asks for a EULA. Keyed by tool name the same
 * way `verifyToolAvailability` keys tools (data-driven; never blanket-pipe
 * `yes` into a blind install).
 */
export const EULA_TOOL_NAMES: string[] = ['gitleaks'];

/** Printed before `mise install` when a known EULA-gated tool is enabled. Never auto-accepts. */
export function eulaPreflightHint(config: AgentenvConfig): string {
  const tools = config.tools || {};
  const flagged = EULA_TOOL_NAMES.filter((name) => tools[name as keyof typeof tools] === true);
  if (flagged.length === 0) return '';
  const tool = flagged[0];
  return `${tool} requires accepting a EULA on first install — run \`mise install ${tool}\` in an interactive terminal and accept it, then re-run \`agentenv apply\`.`;
}

/**
 * Printed instead of silently dropping enabled tools that mise cannot
 * install at all on this platform (see PLATFORM_UNSUPPORTED_TOOLS) — without
 * this, `generateMiseToml`/`getToolsToInstall` quietly excluding them would
 * leave the user thinking those tools installed when they never even ran.
 */
export function platformUnsupportedHint(config: AgentenvConfig): string {
  const tools = config.tools || {};
  const skipped = TOOL_KEYS.filter((key) => tools[key] === true && isPlatformUnsupported(key));
  if (skipped.length === 0) return '';
  return `Skipped on ${process.platform} (no mise backend supports it here): ${skipped.join(', ')}`;
}

export interface EulaDetection {
  eulaTools: string[];
  eulaHint: string;
}

/** Detect a likely interactive-acceptance prompt in captured install output. */
export function detectEulaPrompt(stdout: string, stderr: string): EulaDetection {
  const combined = `${stdout}\n${stderr}`;
  const prompted = EULA_PROMPT_PATTERNS.some((pattern) => pattern.test(combined));
  if (!prompted) return { eulaTools: [], eulaHint: '' };
  const tool = EULA_TOOL_NAMES.find((name) => combined.toLowerCase().includes(name));
  if (tool) {
    return {
      eulaTools: [tool],
      eulaHint: `gitleaks requires accepting a EULA on first install — run \`mise install ${tool}\` in an interactive terminal and accept it, then re-run \`agentenv apply\`.`,
    };
  }
  return {
    eulaTools: [],
    eulaHint:
      'mise install wants an interactive acceptance — run `mise install` in an interactive terminal and accept it, then re-run `agentenv apply`.',
  };
}

export interface MiseInstallResult {
  success: boolean;
  stdout: string;
  stderr: string;
  exitCode: number | null;
  /** Tools (from EULA_TOOL_NAMES) whose EULA likely needs accepting. */
  eulaTools: string[];
  /** One-line instruction for the acceptance case; empty when no prompt. */
  eulaHint: string;
}

/**
 * Run mise install
 * Installs all tools listed in mise.toml
 *
 * Runs via async `spawn` (not `spawnSync`): `mise install` can take tens of
 * seconds (downloading/extracting many tools), and a sync call would block
 * the whole Node event loop for that entire duration — freezing any ora
 * spinner (which redraws via a timer) and delaying every captured line of
 * output until the process exits. `onOutput`, when given, is called with
 * each chunk as it arrives so a caller can stream mise's own progress output
 * live instead of only seeing it after install finishes.
 */
export async function runMiseInstall(
  miseTomlPath: string,
  cwd: string = '.',
  onOutput?: (chunk: string, stream: 'stdout' | 'stderr') => void,
): Promise<MiseInstallResult> {
  const { cwd: spawnCwd, env } = miseSpawnOptions({ cwd, miseTomlPath });
  return new Promise<MiseInstallResult>((resolve) => {
    let child: child_process.ChildProcess;
    try {
      child = child_process.spawn('mise', ['install'], {
        cwd: spawnCwd,
        env,
        stdio: ['ignore', 'pipe', 'pipe'],
      });
    } catch (err) {
      resolve({
        success: false,
        stdout: '',
        stderr: err instanceof Error ? err.message : String(err),
        exitCode: null,
        eulaTools: [],
        eulaHint: '',
      });
      return;
    }

    let stdout = '';
    let stderr = '';
    child.stdout?.setEncoding('utf-8').on('data', (chunk: string) => {
      stdout += chunk;
      onOutput?.(chunk, 'stdout');
    });
    child.stderr?.setEncoding('utf-8').on('data', (chunk: string) => {
      stderr += chunk;
      onOutput?.(chunk, 'stderr');
    });
    child.on('error', (err) => {
      resolve({
        success: false,
        stdout,
        stderr: stderr || err.message,
        exitCode: null,
        eulaTools: [],
        eulaHint: '',
      });
    });
    child.on('close', (code) => {
      const eula = detectEulaPrompt(stdout, stderr);
      resolve({
        success: code === 0,
        stdout,
        stderr,
        exitCode: code,
        eulaTools: eula.eulaTools,
        eulaHint: eula.eulaHint,
      });
    });
  });
}

export interface InstalledToolState {
  installed: boolean;
  versions: string[];
}

/**
 * Parse `mise ls --json` output into installed-tool state, or `null` when the
 * output is not valid JSON in a recognizable shape. mise's real output is an
 * object keyed by tool name mapping to entries like `{version, install_path,
 * installed, active}`; declared-but-uninstalled tools still appear with
 * `installed: false`. A legacy `[{name, version}]` array shape is tolerated
 * so an older/downgraded mise cannot silently regress the caller to "nothing
 * installed". Callers that mutate the store must fail closed on `null` —
 * unrecognized output is never evidence that nothing is installed.
 */
export function parseInstalledToolState(raw: string): Record<string, InstalledToolState> | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }

  const state: Record<string, InstalledToolState> = {};
  if (Array.isArray(parsed)) {
    for (const item of parsed as Array<{ name?: string; version?: string }>) {
      if (typeof item?.name !== 'string') continue;
      const entry = (state[item.name] ??= { installed: true, versions: [] });
      if (typeof item.version === 'string') entry.versions.push(item.version);
    }
    return state;
  }

  if (parsed && typeof parsed === 'object') {
    for (const [name, entries] of Object.entries(parsed as Record<string, unknown>)) {
      const list = Array.isArray(entries)
        ? (entries as Array<{ version?: string; installed?: boolean }>)
        : [];
      state[name] = {
        installed: list.some((entry) => entry.installed === true),
        versions: list
          .map((entry) => (typeof entry.version === 'string' ? entry.version : ''))
          .filter((version) => version !== ''),
      };
    }
    return state;
  }

  return null;
}

/**
 * Tolerant installed-tool state view for read-only callers: unlike
 * `parseInstalledToolState`, unparseable or unrecognized `mise ls --json`
 * output (or an absent mise) yields an empty map rather than `null`.
 */
export function getInstalledToolState(
  raw?: string,
  opts: RunMiseCapturedOptions = {},
): Record<string, InstalledToolState> {
  return parseInstalledToolState(raw ?? runMiseCaptured(['ls', '--json'], opts).stdout) ?? {};
}
