/**
 * Mise Toolchain Integration
 * Handles mise.toml generation and mise commands
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as child_process from 'child_process';
import { AgentenvConfig, BINARY_MAP, TOOL_KEYS, TOOL_TIERS } from '../config/schema.js';
import { resolveBinary } from '../adapters/detect.js';
import { FALLBACK_REQUIRED_TOOLS, requiresFallback } from './fallbacks.js';

// Tool to mise name mappings
export const MISE_TOOL_NAMES: Record<string, string> = {
  ripgrep: 'ripgrep',
  fd: 'fd',
  jq: 'jq',
  rtk: 'rtk',
  ast_grep: 'ast-grep',
  git_delta: 'delta',
  universal_ctags: 'universal-ctags',
  gh: 'gh',
  difftastic: 'difftastic',
  yq: 'yq',
  bat: 'bat',
  eza: 'eza',
  miller: 'miller',
  tokei: 'tokei',
  hyperfine: 'hyperfine',
  fzf: 'fzf',
  just: 'just',
  watchexec: 'watchexec',
  direnv: 'direnv',
};

// Tools that cannot be installed via mise and require fallback
// Based on Phase 0 findings: universal-ctags and tokei are not in mise registry
export { FALLBACK_REQUIRED_TOOLS, requiresFallback };

export interface MiseTool {
  name: string;
  miseName: string;
  version: string;
  tier: number;
  category: string;
}

export interface MiseConfig {
  tools: Record<string, string>;
  env?: Record<string, string>;
  settings?: Record<string, any>;
}

/**
 * Tools agentenv invokes directly are pinned to versions we have verified;
 * everything else resolves to latest. rtk is invoked by agentenv's delegation
 * (its `init` flags are the hook contract), moves fast, and must stay pinned —
 * bump deliberately per plan §10.
 */
export const PINNED_TOOL_VERSIONS: Record<string, string> = {
  rtk: '0.49.0',
};

/**
 * Generate mise.toml content from agentenv config
 */
export function generateMiseToml(
  config: AgentenvConfig,
  customTools: Array<{
    name: string;
    mise_source?: string;
    version?: string;
  }> = [],
): string {
  const lines: string[] = [];

  lines.push('# mise.toml - Generated by agentenv');
  lines.push('# Do not edit directly; edit agentenv.toml instead');
  lines.push('');

  // Tools section
  lines.push('[tools]');

  const tools = config.tools || {};
  const toolKeys = Object.keys(tools) as Array<keyof typeof tools>;

  // Process tools by tier
  const tier1Tools = toolKeys.filter((key) => TOOL_TIERS[key] === 1 && tools[key]);
  const tier2Tools = toolKeys.filter((key) => TOOL_TIERS[key] === 2 && tools[key]);
  const tier3Tools = toolKeys.filter((key) => TOOL_TIERS[key] === 3 && tools[key]);

  // Add enabled tools
  const allEnabledTools = [...tier1Tools, ...tier2Tools, ...tier3Tools];

  for (const toolKey of allEnabledTools) {
    // Skip tools that require fallback installation (not in mise registry)
    if (requiresFallback(toolKey)) {
      continue;
    }
    const miseName = MISE_TOOL_NAMES[toolKey] || toolKey;
    const version = PINNED_TOOL_VERSIONS[miseName] || config.tool_versions?.[toolKey] || 'latest';
    lines.push(`${miseName} = "${version}"`);
  }

  // Add custom tools with mise_source
  for (const ct of customTools) {
    if (ct.mise_source) {
      const version = ct.version || 'latest';
      lines.push(`\n# Custom tool: ${ct.name}`);
      lines.push(`${ct.mise_source} = "${version}"`);
    }
  }

  lines.push('');

  // Env section for agentenv-specific variables
  lines.push('[env]');
  lines.push('AGENTENV_MANAGED = "true"');
  lines.push('');

  return lines.join('\n');
}

/**
 * Directory where agentenv asks mise to place shims (~/.local/bin). Shim files
 * are what make the installed tools resolve by name ("difft", "rg", ...) from
 * any shell — PowerShell, cmd, bash or the agents themselves.
 */
export function shimsDir(): string {
  return path.join(os.homedir(), '.local', 'bin');
}

/**
 * mise's global config directory. `shims_dir` is deliberately NOT honored in a
 * project/`MISE_CONFIG_FILE` config — mise ignores it there with a warning
 * ("ignored for security reasons") — so it must live in the global config.
 */
export function miseGlobalConfigDir(): string {
  return path.join(os.homedir(), '.config', 'mise');
}

export function miseGlobalConfigPath(): string {
  return path.join(miseGlobalConfigDir(), 'config.toml');
}

/**
 * True when a PATH variable entry resolves to the given directory
 * (case-folded on Windows where PATH entries and real paths often differ in
 * case).
 */
export function pathContainsDir(pathVar: string, dir: string): boolean {
  const target = path.resolve(dir);
  const want = process.platform === 'win32' ? target.toLowerCase() : target;
  return pathVar
    .split(path.delimiter)
    .filter((entry) => entry.trim() !== '')
    .some((entry) => {
      const resolved = path.resolve(entry);
      const have = process.platform === 'win32' ? resolved.toLowerCase() : resolved;
      return have === want;
    });
}

/** Whether the shims dir (~/.local/bin) is already resolvable from PATH. */
export function shimsDirOnPath(): boolean {
  return pathContainsDir(process.env.PATH ?? '', shimsDir());
}

/**
 * Line-based insert/update of `shims_dir = "<dir>"` under `[settings]` in a
 * mise config. Surgical on purpose: the global mise config may carry the
 * user's own comments/settings, and a full TOML round-trip would destroy them.
 */
export function upsertShimsDir(content: string, dir: string): string {
  const shimsLine = `shims_dir = "${tomlPath(dir)}"`;
  const lines = content.split('\n');
  const headerIdx = lines.findIndex((line) => /^\s*\[settings\]\s*$/.test(line));
  if (headerIdx === -1) {
    const trimmed = content.trimEnd();
    return trimmed === ''
      ? `[settings]\n${shimsLine}\n`
      : `${trimmed}\n\n[settings]\n${shimsLine}\n`;
  }
  const nextHeader = lines.findIndex((line, i) => i > headerIdx && /^\s*\[[^[]/.test(line));
  const end = nextHeader === -1 ? lines.length : nextHeader;
  const existing = lines.slice(headerIdx, end).findIndex((line) => /^\s*shims_dir\s*=/.test(line));
  if (existing !== -1) {
    lines[headerIdx + existing] = shimsLine;
    return lines.join('\n');
  }
  lines.splice(headerIdx + 1, 0, shimsLine);
  return lines.join('\n');
}

/**
 * Extract the `shims_dir` value mise would honor from `[settings]` in a mise
 * config, or null when it is absent. Used by `agentenv doctor`.
 */
export function getShimsDirValue(content: string): string | null {
  const lines = content.split('\n');
  const headerIdx = lines.findIndex((line) => /^\s*\[settings\]\s*$/.test(line));
  if (headerIdx === -1) return null;
  for (let i = headerIdx + 1; i < lines.length; i++) {
    if (/^\s*\[[^[]/.test(lines[i])) break;
    const match = lines[i].match(/^\s*shims_dir\s*=\s*"([^"]+)"/);
    if (match) return match[1];
  }
  return null;
}

/**
 * Ensure mise's GLOBAL config declares the shims_dir agentenv relies on, and
 * tell the user whether the shims dir is actually on PATH. Idempotent.
 */
export function ensureGlobalShimsDir(): {
  success: boolean;
  message: string;
} {
  const dir = shimsDir();
  const configPath = miseGlobalConfigPath();
  try {
    fs.mkdirSync(miseGlobalConfigDir(), { recursive: true });
    const existing = fs.existsSync(configPath) ? fs.readFileSync(configPath, 'utf-8') : '';
    const updated = upsertShimsDir(existing, dir);
    if (updated !== existing) fs.writeFileSync(configPath, updated);

    const pathLine = shimsDirOnPath()
      ? `${dir} is on PATH`
      : `Add ${dir} to PATH so the shims resolve (Windows: System Properties > Environment Variables > Path)`;
    if (updated !== existing) {
      return {
        success: true,
        message: `mise: set shims_dir in ${configPath}; ${pathLine}`,
      };
    }
    return {
      success: true,
      message: `mise: shims_dir already set (${tomlPath(dir)}); ${pathLine}`,
    };
  } catch (err) {
    return {
      success: false,
      message: `Failed to configure mise shims_dir: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}

/** Format a path for embedding in a TOML string (mise wants forward slashes on Windows). */
function tomlPath(p: string): string {
  return process.platform === 'win32' ? p.replace(/\\/g, '/') : p;
}

/**
 * Save mise.toml to a file
 */
export function saveMiseToml(content: string, outputPath: string): void {
  try {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, content);
  } catch (err) {
    throw new Error(`Failed to save mise.toml: ${err}`, { cause: err });
  }
}

/**
 * Get list of tools to install from config
 */
export function getToolsToInstall(config: AgentenvConfig): Array<{
  name: string;
  miseName: string;
  version: string;
  tier: number;
}> {
  const tools = config.tools || {};
  const toolKeys = Object.keys(tools) as Array<keyof typeof tools>;

  const result: Array<{
    name: string;
    miseName: string;
    version: string;
    tier: number;
  }> = [];

  for (const key of toolKeys) {
    if (tools[key]) {
      // Skip tools that require fallback installation (not in mise registry)
      if (requiresFallback(key)) {
        continue;
      }
      const miseName = MISE_TOOL_NAMES[key] || key;
      result.push({
        name: key,
        miseName,
        version: PINNED_TOOL_VERSIONS[miseName] || config.tool_versions?.[key] || 'latest',
        tier: TOOL_TIERS[key] || 3,
      });
    }
  }

  return result;
}

/**
 * The mise tool names `agentenv update` may safely bump: enabled, non-fallback
 * tools that resolve to `latest`. Pinned tools (rtk's code pin and any
 * `agentenv.toml [tool_versions]` entry) are excluded so `mise up` never moves
 * a version the user (or the hook contract) chose to pin.
 */
export function getUpgradeableTools(config: AgentenvConfig): string[] {
  return getToolsToInstall(config)
    .filter((tool) => tool.version === 'latest')
    .map((tool) => tool.miseName);
}

/**
 * Update mise itself. Unattended (`MISE_YES=1`); surfaces stderr as-is because
 * some install methods (e.g. winget) do not support in-place self-updates and
 * the user must see that instead of a silent no-op.
 */
export async function runMiseSelfUpdate(): Promise<{
  success: boolean;
  output: string;
}> {
  try {
    const result = child_process.spawnSync('mise', ['self-update'], {
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, MISE_YES: '1' },
    });
    const output = (result.stdout || result.stderr || '').trim();
    return { success: result.status === 0, output };
  } catch (err) {
    return {
      success: false,
      output: err instanceof Error ? err.message : String(err),
    };
  }
}

/**
 * Bump the given `mise up` targets to their latest versions within the current
 * config constraints (pins stay put because pinned tools are not passed in).
 */
export async function runMiseUpgrade(
  tools: string[],
  cwd: string,
): Promise<{
  success: boolean;
  stdout: string;
  stderr: string;
  exitCode: number | null;
}> {
  try {
    const result = child_process.spawnSync('mise', ['up', ...tools], {
      cwd,
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    return {
      success: result.status === 0,
      stdout: result.stdout || '',
      stderr: result.stderr || '',
      exitCode: result.status ?? null,
    };
  } catch (err) {
    return {
      success: false,
      stdout: '',
      stderr: err instanceof Error ? err.message : String(err),
      exitCode: null,
    };
  }
}

/**
 * Check if a specific tool is installed via mise
 */
export function isMiseInstalled(): boolean {
  try {
    child_process.execSync('mise --version', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Get mise version
 */
export function getMiseVersion(): string {
  try {
    const output = child_process.execSync('mise --version', { encoding: 'utf-8' });
    return output.trim();
  } catch {
    return 'unknown';
  }
}

/**
 * Check if a specific tool is installed via mise
 */
export function isToolInstalled(toolName: string): boolean {
  try {
    child_process.execSync(`mise which ${toolName}`, { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Install mise itself
 * This should be done by the user before running agentenv
 */
export function ensureMiseInstalled(): {
  success: boolean;
  message: string;
} {
  if (isMiseInstalled()) {
    return {
      success: true,
      message: `mise is already installed (${getMiseVersion()})`,
    };
  }

  return {
    success: false,
    message:
      "mise is not installed. agentenv uses mise to install and manage this project's tools.\n" +
      miseInstallInstructions().join('\n'),
  };
}

/**
 * Platform-specific instructions for installing mise, used for self-diagnosis
 * when `mise` is missing from PATH.
 */
export function miseInstallInstructions(): string[] {
  const lines = ['To install mise, run one of the following:'];

  if (process.platform === 'win32') {
    lines.push('  winget install jdx.mise');
    lines.push('  # or: irm https://mise.jdx.dev/install.ps1 | iex');
  } else if (process.platform === 'darwin') {
    lines.push('  brew install mise');
  } else {
    lines.push('  curl https://mise.jdx.dev/install.sh | sh');
  }

  lines.push('Then open a new terminal so `mise` is available on PATH.');
  lines.push('Full docs: https://mise.jdx.dev/getting-started.html');
  return lines;
}

/**
 * Mark the generated mise.toml as trusted so `mise` (and the shims it creates)
 * actually use it in this directory. Idempotent: re-trusting is a no-op success.
 */
export function trustMiseToml(
  miseTomlPath: string,
  cwd: string = '.',
): {
  success: boolean;
  message: string;
} {
  try {
    const result = child_process.spawnSync('mise', ['trust', miseTomlPath], {
      cwd,
      encoding: 'utf-8',
      stdio: 'pipe',
    });
    if (result.status === 0) {
      return { success: true, message: `Trusted ${miseTomlPath} (mise trust)` };
    }
    return {
      success: false,
      message: `mise trust failed (exit ${result.status ?? 'null'}): ${(
        result.stderr ||
        result.stdout ||
        ''
      ).trim()}`,
    };
  } catch (err) {
    return {
      success: false,
      message: `mise trust errored: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}

/**
 * Turn raw `mise install` output into a truthful one-liner, so "already
 * installed" runs don't imply anything new was fetched.
 */
export function miseInstallOutcome(stdout: string): string {
  const match = stdout.match(/installed (\d+) tools?/);
  if (match) {
    const installed = Number(match[1]);
    if (installed === 0)
      return 'mise install completed (tools already installed, nothing to fetch)';
    return `mise install completed (installed ${installed} tool${installed === 1 ? '' : 's'})`;
  }
  return 'mise install completed';
}

export interface ToolAvailability {
  key: string;
  binary: string;
  onPath: boolean;
}

/**
 * After `mise install`, check which enabled tools actually resolve on PATH so
 * setup/apply can report honestly whether shims are active in this shell.
 */
export function verifyToolAvailability(config: AgentenvConfig): ToolAvailability[] {
  const tools = config.tools || {};
  const result: ToolAvailability[] = [];
  for (const key of TOOL_KEYS) {
    if (tools[key] !== true) continue;
    const binary = BINARY_MAP[key];
    result.push({ key, binary, onPath: resolveBinary(binary) !== null });
  }
  return result;
}

/**
 * Concise, actionable guidance for the case where tools are installed via mise
 * but are not yet resolvable from the current shell.
 */
export function miseActivationHint(): string {
  const lines: string[] = [];
  if (process.platform === 'win32') {
    lines.push('These tools ARE installed via mise and resolve while you work inside this project');
    lines.push(`(shims live in ${shimsDir()}). If one is still not found:`);
    lines.push('  - Open a new terminal in this project and try again, or');
    lines.push('  - Run `mise trust` and `mise install` in the project root.');
    lines.push(
      '  - To also use a tool outside this project, set a global default: `mise use -g <tool>`.',
    );
  } else {
    lines.push('Enable mise in your shell so tools resolve on PATH:');
    lines.push('  echo \'eval "$(mise activate bash)"\' >> ~/.bashrc   # bash');
    lines.push('  echo \'eval "$(mise activate zsh)"\' >> ~/.zshrc     # zsh');
    lines.push('Then start a new terminal.');
  }
  return lines.join('\n');
}

/**
 * Run mise install
 * Installs all tools listed in mise.toml
 */
export async function runMiseInstall(
  miseTomlPath: string,
  cwd: string = '.',
): Promise<{
  success: boolean;
  stdout: string;
  stderr: string;
  exitCode: number | null;
}> {
  try {
    const result = child_process.spawnSync('mise', ['install'], {
      cwd,
      encoding: 'utf-8',
      stdio: 'pipe',
      env: {
        ...process.env,
        // Ensure mise uses the correct config file
        MISE_CONFIG_FILE: miseTomlPath,
      },
    });

    return {
      success: result.status === 0,
      stdout: result.stdout || '',
      stderr: result.stderr || '',
      exitCode: result.status ?? null,
    };
  } catch (err) {
    return {
      success: false,
      stdout: '',
      stderr: err instanceof Error ? err.message : String(err),
      exitCode: null,
    };
  }
}

/**
 * Get installed tool versions via mise
 */
export function getInstalledVersions(): Record<string, string> {
  const versions: Record<string, string> = {};

  try {
    const output = child_process.execSync('mise ls --json', {
      encoding: 'utf-8',
      stdio: 'pipe',
    });

    const tools = JSON.parse(output) as Array<{
      name: string;
      version: string;
    }>;

    for (const tool of tools) {
      versions[tool.name] = tool.version;
    }
  } catch {
    // Ignore errors (mise might not be installed or might not support --json)
  }

  return versions;
}

/**
 * Parse existing mise.toml file
 */
export function parseMiseToml(filePath: string): MiseConfig | null {
  try {
    if (!fs.existsSync(filePath)) {
      return null;
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    return parseToml(content) as MiseConfig;
  } catch {
    return null;
  }
}

/**
 * Simple TOML parser helper
 */
function parseToml(content: string): Record<string, any> {
  const result: Record<string, any> = {};
  let currentTable: Record<string, any> = result;

  const lines = content.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip comments and empty lines
    if (trimmed === '' || trimmed.startsWith('#')) {
      continue;
    }

    // Section header
    if (trimmed.startsWith('[') && trimmed.endsWith(']')) {
      const section = trimmed.slice(1, -1);

      if (section.includes('.')) {
        // Nested section
        const parts = section.split('.');
        let parent: Record<string, any> = result;

        for (let i = 0; i < parts.length - 1; i++) {
          if (!parent[parts[i]]) {
            parent[parts[i]] = {};
          }
          parent = parent[parts[i]];
        }

        currentTable = parent;
      } else {
        if (!result[section]) {
          result[section] = {};
        }
        currentTable = result[section];
      }
      continue;
    }

    // Key-value pair
    const equalsIndex = trimmed.indexOf('=');
    if (equalsIndex > 0) {
      const key = trimmed.slice(0, equalsIndex).trim();
      const value = trimmed.slice(equalsIndex + 1).trim();

      // Remove quotes if present
      let cleanValue: any = value;
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        cleanValue = value.slice(1, -1);
      }

      // Parse boolean
      if (cleanValue.toLowerCase() === 'true') {
        cleanValue = true;
      } else if (cleanValue.toLowerCase() === 'false') {
        cleanValue = false;
      }

      // Parse number
      if (!isNaN(Number(cleanValue))) {
        cleanValue = Number(cleanValue);
      }

      currentTable[key] = cleanValue;
    }
  }

  return result;
}

/**
 * Merge existing mise.toml with new tools
 * Preserves existing tools that are not in the new config
 */
export function mergeMiseConfigs(existing: MiseConfig | null, newConfig: MiseConfig): MiseConfig {
  const result: MiseConfig = {
    tools: { ...newConfig.tools },
    env: { ...newConfig.env },
    settings: { ...newConfig.settings },
  };

  if (existing) {
    // Merge tools - preserve existing versions if not in new config
    for (const [tool, version] of Object.entries(existing.tools || {})) {
      if (!result.tools[tool]) {
        result.tools[tool] = version;
      }
    }

    // Merge env
    if (existing.env) {
      for (const [key, value] of Object.entries(existing.env)) {
        if (!result.env || !result.env[key]) {
          if (!result.env) {
            result.env = {};
          }
          result.env[key] = value;
        }
      }
    }

    // Merge settings
    if (existing.settings) {
      for (const [key, value] of Object.entries(existing.settings)) {
        if (!result.settings || result.settings[key] === undefined) {
          if (!result.settings) {
            result.settings = {};
          }
          result.settings[key] = value;
        }
      }
    }
  }

  return result;
}
