// Package toolchain handles mise.toml generation and mise/rtk invocation.
package toolchain

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/indy2kro/agentenv/cmd/agentenv/internal/config"
)

// ToolMapping maps common tool names to mise registry names.
var ToolMapping = map[string]string{
	"ripgrep":    "ripgrep",
	"rg":         "ripgrep",
	"fd":         "fd",
	"jq":         "jq",
	"rtk":        "rtk",
	"ast-grep":   "ast-grep",
	"sg":         "ast-grep",
	"git-delta":  "delta",
	"delta":      "delta",
	"universal-ctags": "ctags", // Note: not in mise registry, fallback required
	"gh":         "gh",
	"difftastic": "difftastic",
	"difft":      "difftastic",
	"yq":         "yq",
	"bat":        "bat",
	"eza":        "eza",
	"miller":     "miller",
	"mlr":        "miller",
	"tokei":      "tokei",
	"hyperfine":  "hyperfine",
	"fzf":        "fzf",
	"just":       "just",
	"watchexec":  "watchexec",
	"direnv":     "direnv",
}

// BinaryMapping maps mise registry names to actual binary names.
var BinaryMapping = map[string]string{
	"ripgrep":    "rg",
	"fd":         "fd",
	"jq":         "jq",
	"rtk":        "rtk",
	"ast-grep":   "sg",
	"delta":      "delta",
	"gh":         "gh",
	"difftastic": "difft",
	"yq":         "yq",
	"bat":        "bat",
	"eza":        "eza",
	"miller":     "mlr",
	"tokei":      "tokei",
	"hyperfine":  "hyperfine",
	"fzf":        "fzf",
	"just":       "just",
	"watchexec":  "watchexec",
	"direnv":     "direnv",
}

// GenerateMiseTOML generates a mise.toml file from the agentenv config.
func GenerateMiseTOML(cfg *config.Config, outputPath string) error {
	var sb strings.Builder

	// Write header
	sb.WriteString("# mise.toml - Generated by agentenv\n")
	sb.WriteString("# Do not edit directly; edit agentenv.toml instead\n\n")

	// [tools] section
	sb.WriteString("[tools]\n")

	// Add Tier 1 tools
	if cfg.Tools.Ripgrep {
		sb.WriteString(fmt.Sprintf("ripgrep = \"latest\"  # Binary: %s\n", BinaryMapping["ripgrep"]))
	}
	if cfg.Tools.Fd {
		sb.WriteString(fmt.Sprintf("fd = \"latest\"  # Binary: %s\n", BinaryMapping["fd"]))
	}
	if cfg.Tools.Jq {
		sb.WriteString(fmt.Sprintf("jq = \"latest\"  # Binary: %s\n", BinaryMapping["jq"]))
	}
	if cfg.Tools.Rtk {
		sb.WriteString(fmt.Sprintf("rtk = \"latest\"  # Binary: %s\n", BinaryMapping["rtk"]))
	}

	// Add Tier 2 tools
	if cfg.Tools.AstGrep {
		sb.WriteString(fmt.Sprintf("ast-grep = \"latest\"  # Binary: %s\n", BinaryMapping["ast-grep"]))
	}
	if cfg.Tools.GitDelta {
		sb.WriteString(fmt.Sprintf("delta = \"latest\"  # Binary: %s (git-delta)\n", BinaryMapping["delta"]))
	}
	if cfg.Tools.Ctags {
		// universal-ctags is not in mise registry, skip with warning
		// In practice, we'd add a comment here or use a custom tool
	}
	if cfg.Tools.Gh {
		sb.WriteString(fmt.Sprintf("gh = \"latest\"  # Binary: %s\n", BinaryMapping["gh"]))
	}
	if cfg.Tools.Difftastic {
		sb.WriteString(fmt.Sprintf("difftastic = \"latest\"  # Binary: %s\n", BinaryMapping["difftastic"]))
	}

	// Add Tier 3 tools
	if cfg.Tools.Yq {
		sb.WriteString(fmt.Sprintf("yq = \"latest\"  # Binary: %s\n", BinaryMapping["yq"]))
	}
	if cfg.Tools.Bat {
		sb.WriteString(fmt.Sprintf("bat = \"latest\"  # Binary: %s\n", BinaryMapping["bat"]))
	}
	if cfg.Tools.Eza {
		sb.WriteString(fmt.Sprintf("eza = \"latest\"  # Binary: %s\n", BinaryMapping["eza"]))
	}
	if cfg.Tools.Miller {
		sb.WriteString(fmt.Sprintf("miller = \"latest\"  # Binary: %s (mlr)\n", BinaryMapping["miller"]))
	}
	if cfg.Tools.Tokei {
		// tokei requires cargo backend, may not work without Rust
		sb.WriteString(fmt.Sprintf("tokei = \"latest\"  # Binary: %s (requires Rust/cargo)\n", BinaryMapping["tokei"]))
	}
	if cfg.Tools.Hyperfine {
		sb.WriteString(fmt.Sprintf("hyperfine = \"latest\"  # Binary: %s\n", BinaryMapping["hyperfine"]))
	}
	if cfg.Tools.Fzf {
		sb.WriteString(fmt.Sprintf("fzf = \"latest\"  # Binary: %s\n", BinaryMapping["fzf"]))
	}
	if cfg.Tools.Just {
		sb.WriteString(fmt.Sprintf("just = \"latest\"  # Binary: %s\n", BinaryMapping["just"]))
	}
	if cfg.Tools.Watchexec {
		sb.WriteString(fmt.Sprintf("watchexec = \"latest\"  # Binary: %s\n", BinaryMapping["watchexec"]))
	}
	if cfg.Tools.Direnv {
		sb.WriteString(fmt.Sprintf("direnv = \"latest\"  # Binary: %s\n", BinaryMapping["direnv"]))
	}

	// Add custom tools
	for _, ct := range cfg.CustomTools {
		if ct.MiseSource != "" {
			sb.WriteString(fmt.Sprintf("\n# Custom tool: %s\n", ct.Name))
			sb.WriteString(fmt.Sprintf("%s = \"%s\"\n", ct.MiseSource, ct.Version))
		}
	}

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	if err := os.WriteFile(outputPath, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("failed to write mise.toml: %w", err)
	}

	return nil
}

// RunMiseInstall runs `mise install` in the directory containing mise.toml.
func RunMiseInstall(miseTOMLPath string) error {
	// Get the directory containing mise.toml
	dir := filepath.Dir(miseTOMLPath)

	// Check if mise is available
	if _, err := exec.LookPath("mise"); err != nil {
		return fmt.Errorf("mise not found in PATH: %w", err)
	}

	// Run mise install
	cmd := exec.Command("mise", "install")
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("mise install failed: %w", err)
	}

	return nil
}

// RunRTKInit runs `rtk init` for the specified agent.
func RunRTKInit(agent string) error {
	// Map agent name to rtk init flag
	flagMap := map[string]string{
		"claude_code": "--claude",
		"codex_cli":  "--codex",
		"copilot":    "--copilot",
		"opencode":   "--opencode",
	}

	flag, ok := flagMap[agent]
	if !ok {
		return fmt.Errorf("unknown agent: %s", agent)
	}

	// Check if rtk is available
	if _, err := exec.LookPath("rtk"); err != nil {
		return fmt.Errorf("rtk not found in PATH: %w", err)
	}

	// Run rtk init with the appropriate flag
	args := []string{"init"}
	if flag != "" {
		args = append(args, flag)
	}

	cmd := exec.Command("rtk", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("rtk init %s failed: %w", agent, err)
	}

	return nil
}

// GetBinaryName returns the binary name for a given tool name.
func GetBinaryName(toolName string) string {
	if binary, ok := BinaryMapping[toolName]; ok {
		return binary
	}
	// Try to find in ToolMapping
	if registryName, ok := ToolMapping[toolName]; ok {
		return BinaryMapping[registryName]
	}
	return toolName // Fallback to the tool name itself
}
